"""Declarative chart definitions; add a definition to CHARTS to publish a new chart."""
from .events import EVENTS

CHARTS = [{'x_data': 'days_since_ath',
  'value_col': 'drawdown_pct',
  'group_col': 'Cycle',
  'y_data': [{'name': 'Drawdown Cycle 1', 'group': 'Drawdown Cycle 1', 'axis': 'right'},
             {'name': 'Drawdown Cycle 2', 'group': 'Drawdown Cycle 2', 'axis': 'right'},
             {'name': 'Drawdown Cycle 3', 'group': 'Drawdown Cycle 3', 'axis': 'right'},
             {'name': 'Drawdown Cycle 4', 'group': 'Drawdown Cycle 4', 'axis': 'right'},
             {'name': 'Drawdown Cycle 5', 'group': 'Drawdown Cycle 5', 'axis': 'right'}],
  'title': 'Bitcoin Drawdowns From All-Time High',
  'x_label': 'Days Since ATH',
  'filename': 'Bitcoin_ATH_Drawdown',
  'data_source': 'Data Source: Bitview',
  'family': 'cycle',
  'category': 'Cycle Analysis',
  'description': "Bitcoin's drawdowns from each all-time high, aligned at the peak so the depth and "
                 'duration of all five cycles can be compared directly.',
  'featured': False,
  'axes': {'right': {'label': 'Drawdown (%)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'ALL',
  'input': 'drawdown_data.csv'},
 {'x_data': 'days_since_cycle_low',
  'value_col': 'index_value',
  'group_col': 'Cycle',
  'price_scale': 'current_cycle_low',
  'y_data': [{'name': 'Market Cycle 1', 'group': 'Market Cycle 1', 'axis': 'right'},
             {'name': 'Market Cycle 2', 'group': 'Market Cycle 2', 'axis': 'right'},
             {'name': 'Market Cycle 3', 'group': 'Market Cycle 3', 'axis': 'right'},
             {'name': 'Market Cycle 4', 'group': 'Market Cycle 4', 'axis': 'right'},
             {'name': 'Market Cycle 5', 'group': 'Market Cycle 5', 'axis': 'right'},
             {'name': 'Market Cycle 6', 'group': 'Market Cycle 6', 'axis': 'right'}],
  'title': 'Bitcoin Price Performance Since Cycle Low',
  'x_label': 'Days Since Cycle Low',
  'filename': 'Bitcoin_Cycle_Low',
  'data_source': 'Data Source: Bitview',
  'family': 'cycle',
  'category': 'Cycle Analysis',
  'description': "Bitcoin's price performance indexed from each cycle low, aligning six market cycles "
                 'from the day the bear market bottomed.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price Indexed to Current Cycle Low ($)',
                     'unit': 'USD',
                     'mode': 'log'}},
  'default_range': 'ALL',
  'input': 'cycle_low_data.csv'},
 {'x_data': 'days_since_halving',
  'value_col': 'index_value',
  'group_col': 'Era',
  'y_data': [{'name': '2012–16', 'group': '2nd Era', 'axis': 'right'},
             {'name': '2016–20', 'group': '3rd Era', 'axis': 'right'},
             {'name': '2020–24', 'group': '4th Era', 'axis': 'right'},
             {'name': '2024+', 'group': '5th Era', 'axis': 'right'}],
  'title': 'Bitcoin Index Performance Since Halving',
  'x_label': 'Days Since Halving',
  'filename': 'Bitcoin_Halving_Cycle',
  'data_source': 'Data Source: Bitview',
  'family': 'cycle',
  'category': 'Cycle Analysis',
  'description': "Bitcoin's price performance indexed from each halving, aligning the 2012, 2016, 2020 "
                 'and 2024 eras from the day issuance last halved.',
  'featured': False,
  'axes': {'right': {'label': 'Cycle Index Value (1.0 = halving price)',
                     'unit': 'ratio',
                     'mode': 'log'}},
  'default_range': 'ALL',
  'input': 'halving_data.csv'}]
