"""Cycle comparisons: each path is measured in days from a peak, low or halving."""

CHARTS = [{'x_data': 'days_since_ath',
  'value_col': 'drawdown_pct',
  'group_col': 'Cycle',
  'y_data': [{'name': 'Drawdown Cycle 1', 'group': 'Drawdown Cycle 1', 'axis': 'right'},
             {'name': 'Drawdown Cycle 2', 'group': 'Drawdown Cycle 2', 'axis': 'right'},
             {'name': 'Drawdown Cycle 3', 'group': 'Drawdown Cycle 3', 'axis': 'right'},
             {'name': 'Drawdown Cycle 4', 'group': 'Drawdown Cycle 4', 'axis': 'right'},
             {'name': 'Drawdown Cycle 5', 'group': 'Drawdown Cycle 5', 'axis': 'right'}],
  'title': 'Bitcoin Drawdowns',
  'filename': 'Bitcoin_ATH_Drawdown',
  'data_source': 'Data Source: BRK',
  'family': 'cycle',
  'category': 'Cycles & Seasonality',
  'description': 'Compares the depth and duration of Bitcoin’s declines from past cycle peaks.',
  'featured': False,
  'axes': {'right': {'label': 'Drawdown (%)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'ALL',
  'input': 'drawdown_data.csv'},
 {'x_data': 'days_since_cycle_low',
  'value_col': 'index_value',
  'group_col': 'Cycle',
  'price_scale': 'current_cycle_low',
  'y_data': [{'name': 'Market Cycle 1', 'group': 'Market Cycle 1', 'axis': 'right'},
             {'name': 'Market Cycle 2', 'group': 'Market Cycle 2', 'axis': 'right'},
             {'name': 'Market Cycle 3', 'group': 'Market Cycle 3', 'axis': 'right'},
             {'name': 'Market Cycle 4', 'group': 'Market Cycle 4', 'axis': 'right'},
             {'name': 'Market Cycle 5', 'group': 'Market Cycle 5', 'axis': 'right'},
             {'name': 'Market Cycle 6', 'group': 'Market Cycle 6', 'axis': 'right'}],
  'title': 'Bitcoin Cycle Lows',
  'filename': 'Bitcoin_Cycle_Low',
  'data_source': 'Data Source: BRK',
  'family': 'cycle',
  'category': 'Cycles & Seasonality',
  'description': 'Compares Bitcoin’s price paths after cycle lows, scaled to the current cycle’s starting price.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price Indexed to Current Cycle Low ($)',
                     'unit': 'USD',
                     'mode': 'log'}},
  'default_range': 'ALL',
  'input': 'cycle_low_data.csv'},
 {'x_data': 'days_since_halving',
  'value_col': 'index_value',
  'group_col': 'Era',
  'price_scale': 'current_halving',
  'y_data': [{'name': '2012–16', 'group': '2nd Era', 'axis': 'right'},
             {'name': '2016–20', 'group': '3rd Era', 'axis': 'right'},
             {'name': '2020–24', 'group': '4th Era', 'axis': 'right'},
             {'name': '2024+', 'group': '5th Era', 'axis': 'right'}],
  'title': 'Bitcoin Halving Cycles',
  'filename': 'Bitcoin_Halving_Cycle',
  'data_source': 'Data Source: BRK',
  'family': 'cycle',
  'category': 'Cycles & Seasonality',
  'description': 'Compares Bitcoin’s price paths after halvings, scaled to the current halving’s starting price.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price Rebased to Current Halving (USD)',
                     'unit': 'USD',
                     'mode': 'log'}},
  'default_range': 'ALL',
  'input': 'halving_data.csv'}]
