"""Period comparisons share one parameterized transformation."""
CHARTS = [{'filename': 'MTD_Return_By_Year_Percentage',
  'title': 'Bitcoin MTD Returns by Year',
  'family': 'seasonal',
  'category': 'Returns and Performance',
  'description': "Bitcoin's month-to-date return for every calendar year since 2014, shown as a "
                 'daily percentage alongside the median and average across years.',
  'featured': False,
  'period': 'month',
  'indexed': False,
  'default_range': 'ALL',
  'data_source': 'Data Source: Bitview',
  'axes': {'right': {'unit': 'percent', 'label': 'Period return (%)', 'mode': 'linear'}}},
 {'filename': 'Bitcoin_MTD_Return_By_Month_Indexed',
  'title': 'Bitcoin MTD Returns, Indexed',
  'family': 'seasonal',
  'category': 'Returns and Performance',
  'description': "Bitcoin's month-to-date return path for every year since 2014, indexed to the "
                 "current month so each year's shape can be compared day by day.",
  'featured': False,
  'period': 'month',
  'indexed': True,
  'default_range': 'ALL',
  'data_source': 'Data Source: Bitview',
  'axes': {'right': {'unit': 'USD',
                     'label': 'Price indexed to current period baseline (USD)',
                     'mode': 'linear'}}},
 {'filename': 'Bitcoin_YTD_Return_By_Year_Percentage',
  'title': 'Bitcoin YTD Returns by Year',
  'family': 'seasonal',
  'category': 'Returns and Performance',
  'description': "Bitcoin's year-to-date return for every calendar year since 2014, shown as a "
                 'daily percentage alongside the median and average across years.',
  'featured': False,
  'period': 'year',
  'indexed': False,
  'default_range': 'ALL',
  'data_source': 'Data Source: Bitview',
  'axes': {'right': {'unit': 'percent', 'label': 'Period return (%)', 'mode': 'linear'}}},
 {'filename': 'Bitcoin_YTD_Return_By_Year_Indexed',
  'title': 'Bitcoin YTD Returns, Indexed',
  'family': 'seasonal',
  'category': 'Returns and Performance',
  'description': "Bitcoin's year-to-date return path for every year since 2014, indexed to the "
                 "current year so each year's shape can be compared day by day.",
  'featured': False,
  'period': 'year',
  'indexed': True,
  'default_range': 'ALL',
  'data_source': 'Data Source: Bitview',
  'axes': {'right': {'unit': 'USD',
                     'label': 'Price indexed to current period baseline (USD)',
                     'mode': 'linear'}}}]
