"""Seasonal comparisons: this month or year against the same period in past years."""
CHARTS = [{'filename': 'MTD_Return_By_Year_Percentage',
  'title': 'Bitcoin MTD Return History',
  'family': 'seasonal',
  'category': 'Cycles & Seasonality',
  'description': 'Compares Bitcoin’s returns during the current calendar month across different years.',
  'featured': False,
  'period': 'month',
  'indexed': False,
  'default_range': 'ALL',
  'data_source': 'Data Source: BRK',
  'axes': {'right': {'unit': 'percent', 'label': 'Period return (%)', 'mode': 'linear'}}},
 {'filename': 'Bitcoin_MTD_Return_By_Month_Indexed',
  'title': 'Bitcoin MTD Price Paths',
  'family': 'seasonal',
  'category': 'Cycles & Seasonality',
  'description': 'Translates past returns for the same calendar month into price paths from this month’s starting price.',
  'featured': False,
  'period': 'month',
  'indexed': True,
  'default_range': 'ALL',
  'data_source': 'Data Source: BRK',
  'axes': {'right': {'unit': 'USD',
                     'label': 'Price indexed to current period baseline (USD)',
                     'mode': 'linear'}}},
 {'filename': 'Bitcoin_YTD_Return_By_Year_Percentage',
  'default_hidden_series': ['2017'],
  'title': 'Bitcoin YTD Return History',
  'family': 'seasonal',
  'category': 'Cycles & Seasonality',
  'description': 'Compares how Bitcoin’s returns develop through each calendar year.',
  'featured': False,
  'period': 'year',
  'indexed': False,
  'default_range': 'ALL',
  'data_source': 'Data Source: BRK',
  'axes': {'right': {'unit': 'percent', 'label': 'Period return (%)', 'mode': 'linear'}}},
 {'filename': 'Bitcoin_YTD_Return_By_Year_Indexed',
  'default_hidden_series': ['2017'],
  'title': 'Bitcoin YTD Price Paths',
  'family': 'seasonal',
  'category': 'Cycles & Seasonality',
  'description': 'Translates past annual returns into price paths from this year’s starting price.',
  'featured': False,
  'period': 'year',
  'indexed': True,
  'default_range': 'ALL',
  'data_source': 'Data Source: BRK',
  'axes': {'right': {'unit': 'USD',
                     'label': 'Price indexed to current period baseline (USD)',
                     'mode': 'linear'}}}]
