"""Declarative chart definitions; add a definition to CHARTS to publish a new chart."""
from .events import EVENTS

CHARTS = [{'y_data': [{'name': 'Bitcoin Price USD', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Bitcoin Market Cap USD', 'data': 'market_cap', 'axis': 'left'}],
  'title': 'Bitcoin Price',
  'filename': 'Bitcoin_Price',
  'default_presentation': 'candles',
  'default_interval': 'monthly',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price & Trends',
  'description': 'Tracks Bitcoin’s price and market capitalization over time.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Bitcoin Market Cap (USD)', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': '7 Day MA', 'data': '7_day_ma_price_close', 'axis': 'right'},
             {'name': '50 Day MA', 'data': '50_day_ma_price_close', 'axis': 'right'},
             {'name': '200 Day MA', 'data': '200_day_ma_price_close', 'axis': 'right'},
             {'name': '200 Week MA', 'data': '200_week_ma_price_close', 'axis': 'right'},
             {'name': '200 Day MA Multiple', 'data': '200_day_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Moving Averages',
  'filename': 'Bitcoin_Price_Chart_MA',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & Moving Averages', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': '200 Day MA Multiple', 'control_label': 'Multiple', 'weight': 35}],
  'default_presentation': 'candles',
  'default_interval': 'weekly',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price & Trends',
  'description': 'Compares Bitcoin’s price with its short- and long-term moving averages.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '200 Day Moving Average Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Satoshis Per Dollar', 'data': 'sat_per_dollar', 'axis': 'right'}],
  'title': 'Bitcoin Sats Per Dollar',
  'filename': 'Bitcoin_Sats_Per_Dollar',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price & Trends',
  'description': 'Shows how many satoshis one US dollar buys over time.',
  'featured': False,
  'axes': {'right': {'label': 'Satoshis per US Dollar', 'unit': 'sats/USD', 'mode': 'log'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': '30-Day Volatility', 'data': 'volatility_30d', 'axis': 'left'},
             {'name': '180-Day Volatility', 'data': 'volatility_180d', 'axis': 'left'}],
  'title': 'Bitcoin Volatility',
  'filename': 'Bitcoin_Volatility',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': '30-Day & 180-Day Volatility', 'control_label': 'Volatility', 'weight': 35}],
  'default_presentation': 'candles',
  'default_interval': 'weekly',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price & Trends',
  'description': 'Tracks how much Bitcoin’s price fluctuates over shorter and longer periods.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Annualized Volatility', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Supply', 'data': 'supply', 'axis': 'right'},
             {'name': 'New Coins Issued 30 Day MA', 'data': '30_day_ma_subsidy_sum_24h', 'axis': 'left'},
             {'name': 'New Coins Issued 365 Day MA',
              'data': '365_day_ma_subsidy_sum_24h',
              'axis': 'left'}],
  'title': 'Bitcoin Supply and Issuance',
  'filename': 'Bitcoin_Supply',
  'panels': [{'axis': 'left', 'label': 'Daily Issuance', 'control_label': 'Issuance', 'weight': 65},
             {'axis': 'right', 'label': 'Circulating Bitcoin Supply', 'control_label': 'Supply', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': 'Tracks circulating bitcoin and the rate at which new coins are mined.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Supply', 'unit': 'BTC', 'mode': 'log'},
           'left': {'label': 'New Bitcoins Created Each Day', 'unit': 'BTC/day', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Liquid Supply', 'data': 'liquid_supply', 'axis': 'right'},
             {'name': 'Illiquid Supply', 'data': 'illiquid_supply', 'axis': 'right'},
             {'name': 'STH Supply', 'data': 'sth_supply', 'axis': 'right'},
             {'name': 'LTH Supply', 'data': 'lth_supply', 'axis': 'right'},
             {'name': 'Current Supply', 'data': 'supply', 'axis': 'right'}],
  'title': 'Bitcoin Holder Supply',
  'filename': 'Bitcoin_Macro_Supply',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': 'Compares recently moved and dormant bitcoin with short- and long-term holder supply.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Supply', 'unit': 'BTC', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Supply Last Moved Over 1 Year Ago',
              'data': 'supply_pct_1_year_plus',
              'axis': 'left'}],
  'title': 'Bitcoin 1+ Year Supply',
  'filename': 'Bitcoin_1_Year_Supply',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Supply Last Moved Over 1 Year Ago', 'control_label': 'Supply', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': 'Tracks the share of bitcoin that has not moved for over a year.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '1+ Year Supply Percentage', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Supply < 1 Month', 'data': 'utxos_under_1m_old_supply', 'axis': 'right'},
             {'name': 'Supply < 3 Months', 'data': 'utxos_under_3m_old_supply', 'axis': 'right'},
             {'name': 'Supply < 6 Months', 'data': 'utxos_under_6m_old_supply', 'axis': 'right'},
             {'name': 'Supply < 1 Year', 'data': 'utxos_under_1y_old_supply', 'axis': 'right'},
             {'name': 'Supply < 2 Years', 'data': 'utxos_under_2y_old_supply', 'axis': 'right'},
             {'name': 'Supply < 3 Years', 'data': 'utxos_under_3y_old_supply', 'axis': 'right'},
             {'name': 'Supply < 4 Years', 'data': 'utxos_under_4y_old_supply', 'axis': 'right'},
             {'name': 'Supply < 5 Years', 'data': 'utxos_under_5y_old_supply', 'axis': 'right'},
             {'name': 'Supply < 10 Years', 'data': 'utxos_under_10y_old_supply', 'axis': 'right'},
             {'name': 'Current Supply', 'data': 'supply', 'axis': 'right'}],
  'title': 'Bitcoin Supply Age',
  'filename': 'Bitcoin_Supply_Age',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': 'Shows how much bitcoin has moved within different time periods.',
  'featured': False,
  'axes': {'right': {'label': 'Supply (BTC)', 'unit': 'BTC', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Transaction Count', 'data': 'tx_count_sum_24h', 'axis': 'right'},
             {'name': 'Tx Count 30 Day MA', 'data': '30_day_ma_tx_count_sum_24h', 'axis': 'right'},
             {'name': 'Tx Count 365 Day MA', 'data': '365_day_ma_tx_count_sum_24h', 'axis': 'right'}],
  'title': 'Bitcoin Transactions',
  'filename': 'Bitcoin_Transactions',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Tracks the number of transactions confirmed on the Bitcoin network each day.',
  'featured': False,
  'axes': {'right': {'label': 'Daily Transactions', 'unit': 'count', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Fees Paid (USD)', 'data': 'fees_sum_24h_usd', 'axis': 'left'}],
  'title': 'Bitcoin Transaction Fees',
  'filename': 'Bitcoin_Transaction_Fee',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Transaction Fees (USD)', 'control_label': 'Fees', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Tracks the total dollar value of transaction fees paid to miners each day.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Fees In US Dollars', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Transaction Volume', 'data': 'transfer_volume_sum_24h_usd', 'axis': 'left'},
             {'name': 'Transaction Volume 30 Day MA',
              'data': '30_day_ma_transfer_volume_sum_24h_usd',
              'axis': 'left'},
             {'name': 'Transaction Volume 365 Day MA',
              'data': '365_day_ma_transfer_volume_sum_24h_usd',
              'axis': 'left'}],
  'title': 'Bitcoin Transfer Volume',
  'filename': 'Bitcoin_Transaction_Value',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Transaction Volume & Moving Averages', 'control_label': 'Volume', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Tracks the dollar value of bitcoin transferred on-chain over time.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Transaction Volume', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Active Addresses', 'data': 'daily_active_addresses_sending', 'axis': 'left'},
             {'name': 'Active Addresses 30 Day MA',
              'data': '30_day_ma_daily_active_addresses_sending',
              'axis': 'left'},
             {'name': 'Active Addresses 365 Day MA',
              'data': '365_day_ma_daily_active_addresses_sending',
              'axis': 'left'}],
  'title': 'Bitcoin Active Addresses',
  'filename': 'Bitcoin_Active_Addresses',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Active Addresses & Moving Averages', 'control_label': 'Addresses', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Tracks daily address activity on the Bitcoin network.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Active Addresses', 'unit': 'count', 'mode': 'linear'}},
  'default_range': '10Y'},
 {'y_data': [{'name': '>1 sat', 'data': 'addrs_over_1sat_addr_count', 'axis': 'right'},
             {'name': '>10 sats', 'data': 'addrs_over_10sats_addr_count', 'axis': 'right'},
             {'name': '>100 sats', 'data': 'addrs_over_100sats_addr_count', 'axis': 'right'},
             {'name': '>1k sats', 'data': 'addrs_over_1k_sats_addr_count', 'axis': 'right'},
             {'name': '>10k sats', 'data': 'addrs_over_10k_sats_addr_count', 'axis': 'right'},
             {'name': '>100k sats', 'data': 'addrs_over_100k_sats_addr_count', 'axis': 'right'},
             {'name': '>1M sats', 'data': 'addrs_over_1m_sats_addr_count', 'axis': 'right'},
             {'name': '>10M sats', 'data': 'addrs_over_10m_sats_addr_count', 'axis': 'right'},
             {'name': '>1 BTC', 'data': 'addrs_over_1btc_addr_count', 'axis': 'right'},
             {'name': '>10 BTC', 'data': 'addrs_over_10btc_addr_count', 'axis': 'right'},
             {'name': '>100 BTC', 'data': 'addrs_over_100btc_addr_count', 'axis': 'right'},
             {'name': '>1k BTC', 'data': 'addrs_over_1k_btc_addr_count', 'axis': 'right'},
             {'name': '>10k BTC', 'data': 'addrs_over_10k_btc_addr_count', 'axis': 'right'}],
  'title': 'Bitcoin Address Balances',
  'filename': 'Bitcoin_Address_Balance',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Tracks the number of Bitcoin addresses holding different minimum balances.',
  'featured': False,
  'axes': {'right': {'label': 'Address Count', 'unit': 'count', 'mode': 'linear'}},
  'default_range': 'ALL'},
 {'y_data': [{'name': 'Hash Rate', 'data': 'hash_rate', 'axis': 'right'},
             {'name': 'Hash Rate 30 Day MA', 'data': '30_day_ma_hash_rate', 'axis': 'right'},
             {'name': 'Hash Rate 365 Day MA', 'data': '365_day_ma_hash_rate', 'axis': 'right'}],
  'title': 'Bitcoin Hashrate',
  'filename': 'Bitcoin_Hashrate_Price',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Tracks the computing power committed to mining and securing Bitcoin.',
  'featured': False,
  'axes': {'right': {'label': 'Hashrate', 'unit': 'hashrate', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Hash Rate 30-Day MA', 'data': '30_day_ma_hash_rate', 'axis': 'left'},
             {'name': 'Hash Rate 60-Day MA', 'data': '60_day_ma_hash_rate', 'axis': 'left'}],
  'title': 'Bitcoin Hash Ribbons',
  'filename': 'Bitcoin_Hash_Ribbons',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Hashrate Moving Averages', 'control_label': 'Hashrate', 'weight': 35}],
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Compares hashrate trends to highlight periods of miner stress and recovery.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hashrate', 'unit': 'hashrate', 'mode': 'log'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Difficulty', 'data': 'difficulty', 'axis': 'right'}],
  'title': 'Bitcoin Mining Difficulty',
  'filename': 'Bitcoin_Difficulty',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Tracks how difficult it is to mine a Bitcoin block.',
  'featured': False,
  'axes': {'right': {'label': 'Difficulty', 'unit': 'count', 'mode': 'log'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Hash Price ($/TH/s)', 'data': 'hash_price_ths', 'axis': 'left'}],
  'title': 'Bitcoin Hashprice',
  'filename': 'Bitcoin_Hash_Price',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Hash Price', 'control_label': 'Hash Price', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Tracks daily mining revenue per unit of computing power.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hash Price ($/TH/s/day)', 'unit': 'USD/TH/s/day', 'mode': 'log'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Miner Revenue', 'data': 'coinbase_sum_24h_usd', 'axis': 'left'},
             {'name': 'Miner Revenue 30 Day MA',
              'data': '30_day_ma_coinbase_sum_24h_usd',
              'axis': 'left'},
             {'name': 'Miner Revenue 365 Day MA',
              'data': '365_day_ma_coinbase_sum_24h_usd',
              'axis': 'left'}],
  'title': 'Bitcoin Miner Revenue',
  'filename': 'Bitcoin_Miner_Revenue',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Miner Revenue & Moving Averages', 'control_label': 'Revenue', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Tracks the dollar value miners earn from block subsidies and transaction fees.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Miner Revenue', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Puell Multiple', 'data': 'puell_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Puell Multiple',
  'filename': 'Bitcoin_Puell_Multiple',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Puell Multiple', 'control_label': 'Multiple', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining & Security',
  'description': 'Compares the daily value of newly mined bitcoin with its yearly average.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Puell Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Thermocap Price', 'data': 'thermocap_price', 'axis': 'right'},
             {'name': '4x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_4',
              'axis': 'right'},
             {'name': '8x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_8',
              'axis': 'right'},
             {'name': '16x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_16',
              'axis': 'right'},
             {'name': '32x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_32',
              'axis': 'right'}],
  'title': 'Bitcoin Thermocap',
  'filename': 'Bitcoin_Thermocap_Multiples',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with valuation levels based on cumulative miner revenue.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Realized Price', 'data': 'realized_price', 'axis': 'right'},
             {'name': 'STH Realized Price', 'data': 'sth_realized_price', 'axis': 'right'},
             {'name': 'LTH Realized Price', 'data': 'lth_realized_price', 'axis': 'right'},
             {'name': '2x Realized Price', 'data': 'realizedcap_multiple_2', 'axis': 'right'},
             {'name': '3x Realized Price', 'data': 'realizedcap_multiple_3', 'axis': 'right'},
             {'name': '5x Realized Price', 'data': 'realizedcap_multiple_5', 'axis': 'right'},
             {'name': 'Realized Price Multiple', 'data': 'mvrv', 'axis': 'left'}],
  'title': 'Bitcoin Realized Price',
  'filename': 'Bitcoin_Realized_Price',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & Realized Price Models', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Realized Price Multiple (MVRV)', 'control_label': 'Multiple', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with the average price at which coins last moved on-chain.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'MVRV Ratio', 'unit': 'ratio', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'NVT Price · 30 Day', 'data': 'nvt_price_30d', 'axis': 'right'},
             {'name': 'NVT Price · 90 Day', 'data': 'nvt_price_90d', 'axis': 'right'},
             {'name': 'NVT Price · 365 Day', 'data': 'nvt_price_365d', 'axis': 'right'},
             {'name': 'NVT Price Multiple · 90 Day', 'data': 'nvt_price_multiple_90d', 'axis': 'left'}],
  'title': 'Bitcoin NVT Price',
  'filename': 'Bitcoin_NVT_Price',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & NVT Price Models', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'NVT Price Multiple', 'control_label': 'Multiple', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with valuation models based on on-chain transfer volume.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'NVT Price Multiple', 'unit': 'ratio', 'mode': 'linear',
                    'reference_lines': [{'value': 1.0, 'label': 'Model price · 1.0×'}]}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Net Unrealized Profit Loss', 'data': 'nupl', 'axis': 'left'}],
  'title': 'Bitcoin NUPL',
  'filename': 'Bitcoin_NUPL',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Net Unrealized Profit/Loss', 'control_label': 'NUPL', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Sentiment',
  'description': 'Shows the market’s unrealized profit or loss relative to Bitcoin’s total value.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'NUPL Ratio', 'unit': 'ratio', 'mode': 'linear',
                    'band_range': [-0.25, 1.0],
                    'value_bands': [
                        {'lower': None, 'upper': 0.0, 'label': 'Capitulation · <0', 'color': '#E87878'},
                        {'lower': 0.0, 'upper': 0.25, 'label': 'Hope / Fear · 0–0.25', 'color': '#DDA76B'},
                        {'lower': 0.25, 'upper': 0.5, 'label': 'Optimism / Anxiety · 0.25–0.50', 'color': '#D6C778'},
                        {'lower': 0.5, 'upper': 0.75, 'label': 'Belief / Denial · 0.50–0.75', 'color': '#78C99A'},
                        {'lower': 0.75, 'upper': None, 'label': 'Euphoria / Greed · ≥0.75', 'color': '#6D9EFF'},
                    ]}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Reserve Risk', 'data': 'reserve_risk_calc', 'axis': 'left'}],
  'title': 'Bitcoin Reserve Risk',
  'filename': 'Bitcoin_HODL_Bank',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Reserve Risk', 'control_label': 'Reserve Risk', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Sentiment',
  'description': 'Compares Bitcoin’s price with a measure of holders’ willingness to keep their coins.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Reserve Risk', 'unit': 'ratio', 'mode': 'log'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'SOPR', 'data': 'sopr_24h', 'axis': 'left'}],
  'title': 'Bitcoin SOPR',
  'filename': 'Bitcoin_SOPR',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Spent Output Profit Ratio', 'control_label': 'SOPR', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2012-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Sentiment',
  'description': 'Shows whether coins moving on-chain are doing so at a profit or loss.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'SOPR', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Supply in Profit %', 'data': 'supply_in_profit_pct', 'axis': 'left'},
             {'name': 'Supply in Loss %', 'data': 'supply_in_loss_pct', 'axis': 'left'}],
  'title': 'Bitcoin Supply Profitability',
  'filename': 'Bitcoin_Supply_Profit_Loss',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Supply in Profit vs Loss', 'control_label': 'Supply', 'weight': 35}],
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Sentiment',
  'description': 'Shows the share of bitcoin in profit or loss based on the price when coins last moved.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '% of Supply', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Power Expense ($0.04/kWh)', 'data': 'electricity_cost_4c', 'axis': 'right'},
             {'name': 'Power Expense ($0.06/kWh)', 'data': 'electricity_cost_6c', 'axis': 'right'},
             {'name': 'Hayes Network Price Per BTC',
              'data': 'hayes_network_price',
              'axis': 'right'},
             {'name': 'Hayes Price Multiple', 'data': 'hayes_network_price_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Electricity Cost',
  'filename': 'Bitcoin_Production_Price',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & Electricity Cost', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Hayes Price Multiple', 'control_label': 'Multiple', 'weight': 35}],
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: BRK, Coin Metrics',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with mining cost estimates based on electricity use.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hayes Price Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Power Law Price', 'data': 'power_law_price', 'axis': 'right'},
             {'name': 'Undervalued boundary · 0.58×', 'data': 'power_law_price_band_058', 'axis': 'right', 'line_style': 'dashed'},
             {'name': 'Overvalued boundary · 1.73×', 'data': 'power_law_price_band_173', 'axis': 'right', 'line_style': 'dashed'},
             {'name': 'Extremely overvalued boundary · 3×', 'data': 'power_law_price_band_300', 'axis': 'right', 'line_style': 'dashed'},
             {'name': 'BTC Price / Power Law Price',
              'data': 'power_law_price_multiple',
              'axis': 'left'}],
  'title': 'Bitcoin Power Law',
  'filename': 'Bitcoin_Power_Law_Model',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & Power Law Value', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Price / Power Law Value', 'control_label': 'Multiple', 'weight': 35}],
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with a growth model based on the network’s age.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log',
                    'band_anchor': 'power_law_price',
                    'band_labels': False,
                    'value_bands': [
                        {'lower': None, 'upper': 'power_law_price_band_058', 'label': 'Undervalued · <0.58×', 'color': '#78C99A'},
                        {'lower': 'power_law_price_band_058', 'upper': 'power_law_price', 'label': 'Below fair value · 0.58–1×', 'color': '#5FD4D0'},
                        {'lower': 'power_law_price', 'upper': 'power_law_price_band_173', 'label': 'Above fair value · 1–1.73×', 'color': '#6D9EFF'},
                        {'lower': 'power_law_price_band_173', 'upper': 'power_law_price_band_300', 'label': 'Overvalued · 1.73–3×', 'color': '#DDA76B'},
                        {'lower': 'power_law_price_band_300', 'upper': None, 'label': 'Extremely overvalued · ≥3×', 'color': '#E87878'},
                    ]},
           'left': {'label': 'BTC Price / Power Law Price', 'unit': 'ratio', 'mode': 'linear',
                    'band_range': [0, 3], 'band_fill': False,
                    'value_bands': [
                        {'lower': None, 'upper': 0.58, 'label': 'Undervalued · <0.58×', 'color': '#78C99A'},
                        {'lower': 0.58, 'upper': 1.0, 'label': 'Below fair value · 0.58–1×', 'color': '#5FD4D0'},
                        {'lower': 1.0, 'upper': 1.73, 'label': 'Above fair value · 1–1.73×', 'color': '#6D9EFF'},
                        {'lower': 1.73, 'upper': 3.0, 'label': 'Overvalued · 1.73–3×', 'color': '#DDA76B'},
                        {'lower': 3.0, 'upper': None, 'label': 'Extremely overvalued · ≥3×', 'color': '#E87878'},
                    ]}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Metcalfe Value (Any Balance)',
              'data': 'metcalfe_value',
              'axis': 'right'},
             {'name': 'BTC Price / Metcalfe Value', 'data': 'metcalfe_price_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Metcalfe Model',
  'filename': 'Bitcoin_Metcalfe_Model',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price & Metcalfe Value', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Price / Metcalfe Value', 'control_label': 'Multiple', 'weight': 35}],
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Valuation Models',
  'description': 'Compares Bitcoin’s price with a valuation model based on addresses holding bitcoin.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'BTC Price / Metcalfe Value', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Gold Market Cap', 'data': 'gold_market_cap_btc_price', 'axis': 'right'},
             {'name': 'Silver Market Cap', 'data': 'silver_market_cap_btc_price', 'axis': 'right'},
             {'name': 'Gold Jewellery', 'data': 'gold_jewellery_market_cap_btc_price', 'axis': 'right'},
             {'name': 'Gold Private Investment',
              'data': 'gold_private_investment_market_cap_btc_price',
              'axis': 'right'},
             {'name': 'Gold Country Holdings',
              'data': 'gold_official_country_holdings_market_cap_btc_price',
              'axis': 'right'},
             {'name': 'Gold Other / Industrial',
              'data': 'gold_other_market_cap_btc_price',
              'axis': 'right'}],
  'title': 'Bitcoin vs Precious Metals',
  'filename': 'Bitcoin_Gold',
  'data_source': 'Data Source: BRK, Yahoo Finance, World Gold Council',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': 'Shows Bitcoin’s implied price at the market values of gold and silver.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Meta', 'data': 'META_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Amazon', 'data': 'AMZN_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Alphabet', 'data': 'GOOGL_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Microsoft', 'data': 'MSFT_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Apple', 'data': 'AAPL_market_cap_btc_price', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin vs Big Tech',
  'filename': 'Bitcoin_RV_stocks',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': 'Shows Bitcoin’s implied price at the market values of major technology companies.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'NVIDIA', 'data': 'NVDA_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Broadcom', 'data': 'AVGO_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'TSMC', 'data': 'TSM_market_cap_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Samsung Electronics',
              'data': '005930.KS_market_cap_btc_price',
              'optional': True,
              'axis': 'right'},
             {'name': 'Micron', 'data': 'MU_market_cap_btc_price', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin vs Semiconductors',
  'filename': 'Bitcoin_RV_Semiconductors',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': '2015-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': 'Shows Bitcoin’s implied price at the market values of major semiconductor companies.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'United States', 'data': 'united_states_m0_btc_price', 'axis': 'right'},
             {'name': 'China', 'data': 'china_m0_btc_price', 'axis': 'right'},
             {'name': 'Eurozone', 'data': 'eurozone_m0_btc_price', 'axis': 'right'},
             {'name': 'Japan', 'data': 'japan_m0_btc_price', 'axis': 'right'},
             {'name': 'United Kingdom', 'data': 'united_kingdom_m0_btc_price', 'axis': 'right'},
             {'name': 'Switzerland', 'data': 'switzerland_m0_btc_price', 'axis': 'right'},
             {'name': 'India', 'data': 'india_m0_btc_price', 'axis': 'right'},
             {'name': 'Australia', 'data': 'australia_m0_btc_price', 'axis': 'right'},
             {'name': 'Russia', 'data': 'russia_m0_btc_price', 'axis': 'right'}],
  'title': 'Bitcoin vs Base Money',
  'filename': 'Bitcoin_M0',
  'data_source': 'Data Source: BRK, central bank M0 data',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': 'Shows Bitcoin’s implied price if its market value matched major economies’ monetary bases.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin YOY Return', 'data': 'price_close_yoy_change', 'axis': 'left'},
             {'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'}],
  'title': 'Bitcoin YoY Return',
  'filter_start_date': '2015-01-01',
  'filename': 'Bitcoin_YOY_Return_Comparison',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Bitcoin Year-Over-Year Return', 'control_label': 'YoY Return', 'weight': 35}],
  'default_presentation': 'candles',
  'default_interval': 'weekly',
  'data_source': 'Data Source: BRK',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Tracks Bitcoin’s percentage price change over the preceding twelve months.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Year Over Year Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Bitcoin 4 Year CAGR', 'data': 'price_close_4y_cagr', 'axis': 'left'}],
  'title': 'Bitcoin 4-Year CAGR',
  'filter_start_date': '2015-01-01',
  'filename': 'Bitcoin_CAGR',
  'panels': [{'axis': 'right', 'label': 'Bitcoin Price', 'control_label': 'Price', 'weight': 65},
             {'axis': 'left', 'label': 'Bitcoin 4-Year CAGR', 'control_label': 'CAGR', 'weight': 35}],
  'default_presentation': 'candles',
  'default_interval': 'weekly',
  'data_source': 'Data Source: BRK',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Shows Bitcoin’s annualized return over rolling four-year periods.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '4 Year CAGR (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '10Y'},
 {'y_data': [{'name': 'Bitcoin', 'data': 'price_close_4y_cagr', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_4y_cagr', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_4y_cagr',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_4y_cagr',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin CAGR Comparison',
  'filename': 'Bitcoin_CAGR_Comparison',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': '2015-05-01',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Compares Bitcoin’s annualized four-year return with other assets.',
  'featured': False,
  'axes': {'right': {'label': '4 Year CAGR (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'y_data': [{'name': 'Bitcoin', 'data': 'price_close_mtd_change', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_mtd_change', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_mtd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_mtd_change',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin MTD Benchmark Returns',
  'filename': 'Bitcoin_MTD_Return_Comparison',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': 'report_month_start',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Compares Bitcoin’s return this month with core market benchmarks.',
  'featured': False,
  'axes': {'right': {'label': 'Month To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'MTD'},
 {'y_data': [{'name': 'Bitcoin', 'data': 'price_close_ytd_change', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_ytd_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_ytd_change',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin YTD Benchmark Returns',
  'filename': 'Bitcoin_YTD_Return_Comparison',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': 'report_year_start',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Compares Bitcoin’s return this year with core market benchmarks.',
  'featured': False,
  'axes': {'right': {'label': 'Year To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'YTD'},
 {'y_data': [{'name': 'BTC', 'data': 'price_close_ytd_change', 'axis': 'right'},
             {'name': 'SPY', 'data': 'SPY_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'QQQ', 'data': 'QQQ_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'Russell 2000 Small Caps', 'data': 'IWM_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'VXUS', 'data': 'VXUS_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLK', 'data': 'XLK_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLF', 'data': 'XLF_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLE', 'data': 'XLE_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLRE', 'data': 'XLRE_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'DXY', 'data': 'DX-Y.NYB_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'GLD', 'data': 'GLD_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'AGG', 'data': 'AGG_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'SPGSCI', 'data': '^SPGSCI_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'MSTR', 'data': 'MSTR_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'XYZ', 'data': 'XYZ_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'COIN', 'data': 'COIN_close_ytd_change', 'optional': True, 'axis': 'right'},
             {'name': 'WGMI', 'data': 'WGMI_close_ytd_change', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin YTD Market Returns',
  'filename': 'Bitcoin_YTD_Return_Comparison_full',
  'data_source': 'Data Source: BRK, Yahoo Finance',
  'filter_start_date': 'report_year_start',
  'family': 'timeseries',
  'category': 'Returns & Comparisons',
  'description': 'Compares Bitcoin’s return this year across a broader mix of markets, sectors and stocks.',
  'featured': False,
  'axes': {'right': {'label': 'Year To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'YTD'}]
