"""Declarative chart definitions; add a definition to CHARTS to publish a new chart."""
from .events import EVENTS

CHARTS = [{'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price USD', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Bitcoin Marketcap USD', 'data': 'market_cap', 'axis': 'left'}],
  'title': 'Bitcoin Price',
  'x_label': 'Date',
  'filename': 'Bitcoin_Price',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Bitcoin's price and market capitalization in US dollars, from the earliest exchange "
                 'data through the most recent daily close.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Bitcoin Market Cap (USD)', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': '7 Day MA', 'data': '7_day_ma_price_close', 'axis': 'right'},
             {'name': '50 Day MA', 'data': '50_day_ma_price_close', 'axis': 'right'},
             {'name': '200 Day MA', 'data': '200_day_ma_price_close', 'axis': 'right'},
             {'name': '200 Week MA', 'data': '200_week_ma_price_close', 'axis': 'right'},
             {'name': '200 Day MA Multiple', 'data': '200_day_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Price Moving Averages',
  'x_label': 'Date',
  'filename': 'Bitcoin_Price_Chart_MA',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Bitcoin's price against its 7, 50 and 200-day and 200-week moving averages, with the "
                 'multiple of price to the 200-day average.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '200 Day Moving Average Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Satoshis Per Dollar', 'data': 'sat_per_dollar', 'axis': 'right'},
             {'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'left'}],
  'title': 'Bitcoin Satoshis Per Dollar',
  'x_label': 'Date',
  'filename': 'Bitcoin_Sats_Per_Dollar',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Satoshis per dollar expresses Bitcoin's price inverted: how many of the smallest "
                 'units, one hundred-millionth of a coin, one dollar buys.',
  'featured': False,
  'axes': {'right': {'label': 'Satoshis Per Dollar | Amount Of Bitcoin You Can Purchase Per $1',
                     'unit': 'sats/USD',
                     'mode': 'log'},
           'left': {'label': '1 Full Bitcoin Price', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': '30-Day Volatility', 'data': 'VtyDayRet30d', 'axis': 'left'},
             {'name': '180-Day Volatility', 'data': 'VtyDayRet180d', 'axis': 'left'}],
  'title': 'Bitcoin Volatility',
  'x_label': 'Date',
  'filename': 'Bitcoin_Volatility',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Bitcoin's realized volatility, the annualized standard deviation of daily returns, "
                 'measured over rolling 30-day and 180-day windows.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Annualized Volatility', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Supply', 'data': 'supply', 'axis': 'right'},
             {'name': 'New Coins Issued 30 Day MA', 'data': '30_day_ma_subsidy_sum_24h', 'axis': 'left'},
             {'name': 'New Coins Issued 365 Day MA',
              'data': '365_day_ma_subsidy_sum_24h',
              'axis': 'left'}],
  'title': 'Bitcoin Supply & Daily Issuance',
  'x_label': 'Date',
  'filename': 'Bitcoin_Supply',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': "Bitcoin's circulating supply against daily new issuance, the coins created by each "
                 'block subsidy, smoothed over 30-day and 365-day windows.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Supply', 'unit': 'BTC', 'mode': 'log'},
           'left': {'label': 'New Bitcoins Created Each Day', 'unit': 'BTC/day', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Liquid Supply', 'data': 'liquid_supply', 'axis': 'left'},
             {'name': 'Illiquid Supply', 'data': 'illiquid_supply', 'axis': 'left'},
             {'name': 'STH Supply', 'data': 'sth_supply', 'axis': 'left'},
             {'name': 'LTH Supply', 'data': 'lth_supply', 'axis': 'left'},
             {'name': 'Current Supply', 'data': 'supply', 'axis': 'left'}],
  'title': 'Bitcoin Macro Supply',
  'x_label': 'Date',
  'filename': 'Bitcoin_Macro_Supply',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': "Bitcoin's supply split by liquidity and holding period, separating liquid from "
                 'illiquid coins and short-term from long-term holder balances.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Bitcoins Supply', 'unit': 'BTC', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Supply Last Moved Over 1 Year Ago',
              'data': 'supply_pct_1_year_plus',
              'axis': 'left'}],
  'title': 'Bitcoin 1+ Year Supply',
  'x_label': 'Date',
  'filename': 'Bitcoin_1_Year_Supply',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': 'The share of circulating Bitcoin last moved more than one year ago, measuring dormant '
                 'supply rather than coins active during the past year.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '1+ Year Supply Percentage', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Supply < 1 Month', 'data': 'utxos_under_1m_old_supply', 'axis': 'left'},
             {'name': 'Supply < 3 Months', 'data': 'utxos_under_3m_old_supply', 'axis': 'left'},
             {'name': 'Supply < 6 Months', 'data': 'utxos_under_6m_old_supply', 'axis': 'left'},
             {'name': 'Supply < 1 Year', 'data': 'utxos_under_1y_old_supply', 'axis': 'left'},
             {'name': 'Supply < 2 Years', 'data': 'utxos_under_2y_old_supply', 'axis': 'left'},
             {'name': 'Supply < 3 Years', 'data': 'utxos_under_3y_old_supply', 'axis': 'left'},
             {'name': 'Supply < 4 Years', 'data': 'utxos_under_4y_old_supply', 'axis': 'left'},
             {'name': 'Supply < 5 Years', 'data': 'utxos_under_5y_old_supply', 'axis': 'left'},
             {'name': 'Supply < 10 Years', 'data': 'utxos_under_10y_old_supply', 'axis': 'left'},
             {'name': 'Current Supply', 'data': 'supply', 'axis': 'left'}],
  'title': 'Bitcoin Supply Age Distribution',
  'x_label': 'Date',
  'filename': 'Bitcoin_Supply_Age',
  'data_source': 'Data Source: BRK',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Supply',
  'description': "Bitcoin's supply grouped by how recently each coin last moved, from under one month "
                 'to over ten years, showing the distribution of holding periods.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Supply (BTC)', 'unit': 'BTC', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Transaction Count', 'data': 'tx_count_sum_24h', 'axis': 'right'},
             {'name': 'Tx Count 30 Day MA', 'data': '30_day_ma_tx_count_sum_24h', 'axis': 'right'},
             {'name': 'Tx Count 365 Day MA', 'data': '365_day_ma_tx_count_sum_24h', 'axis': 'right'}],
  'title': 'Bitcoin Transactions',
  'x_label': 'Date',
  'filename': 'Bitcoin_Transactions',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'The number of Bitcoin transactions confirmed each day, with 30-day and 365-day moving '
                 'averages to separate short-term noise from the trend.',
  'featured': False,
  'axes': {'right': {'label': 'Daily Transactions', 'unit': 'count', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Fees Paid (USD)', 'data': 'fees_sum_24h_usd', 'axis': 'left'}],
  'title': 'Bitcoin Transaction Fees',
  'x_label': 'Date',
  'filename': 'Bitcoin_Transaction_Fee',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Total Bitcoin transaction fees paid to miners each day in US dollars, the portion of '
                 'miner revenue that does not come from the block subsidy.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Fees In US Dollars', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Transaction Volume', 'data': 'transfer_volume_sum_24h_usd', 'axis': 'left'},
             {'name': 'Transaction Volume 30 Day MA',
              'data': '30_day_ma_transfer_volume_sum_24h_usd',
              'axis': 'left'},
             {'name': 'Transaction Volume 365 Day MA',
              'data': '365_day_ma_transfer_volume_sum_24h_usd',
              'axis': 'left'}],
  'title': 'Bitcoin Transaction Volume',
  'x_label': 'Date',
  'filename': 'Bitcoin_Transaction_Value',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Bitcoin transaction volume is the total value settled on-chain each day, smoothed '
                 'over 30-day and 365-day windows to show the underlying trend.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Transaction Volume', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Active Addresses', 'data': 'daily_active_addresses_sending', 'axis': 'left'},
             {'name': 'Active Addresses 30 Day MA',
              'data': '30_day_ma_daily_active_addresses_sending',
              'axis': 'left'},
             {'name': 'Active Addresses 365 Day MA',
              'data': '365_day_ma_daily_active_addresses_sending',
              'axis': 'left'}],
  'title': 'Bitcoin Active Addresses',
  'x_label': 'Date',
  'filename': 'Bitcoin_Active_Addresses',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'Active addresses count the distinct Bitcoin addresses sending or receiving in a day, '
                 'a measure of network use smoothed over 30 and 365 days.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Active Addresses', 'unit': 'count', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': '>1 sat', 'data': 'addrs_over_1sat_addr_count', 'axis': 'left'},
             {'name': '>10 sats', 'data': 'addrs_over_10sats_addr_count', 'axis': 'left'},
             {'name': '>100 sats', 'data': 'addrs_over_100sats_addr_count', 'axis': 'left'},
             {'name': '>1k sats', 'data': 'addrs_over_1k_sats_addr_count', 'axis': 'left'},
             {'name': '>10k sats', 'data': 'addrs_over_10k_sats_addr_count', 'axis': 'left'},
             {'name': '>100k sats', 'data': 'addrs_over_100k_sats_addr_count', 'axis': 'left'},
             {'name': '>1M sats', 'data': 'addrs_over_1m_sats_addr_count', 'axis': 'left'},
             {'name': '>10M sats', 'data': 'addrs_over_10m_sats_addr_count', 'axis': 'left'},
             {'name': '>1 BTC', 'data': 'addrs_over_1btc_addr_count', 'axis': 'left'},
             {'name': '>10 BTC', 'data': 'addrs_over_10btc_addr_count', 'axis': 'left'},
             {'name': '>100 BTC', 'data': 'addrs_over_100btc_addr_count', 'axis': 'left'},
             {'name': '>1k BTC', 'data': 'addrs_over_1k_btc_addr_count', 'axis': 'left'},
             {'name': '>10k BTC', 'data': 'addrs_over_10k_btc_addr_count', 'axis': 'left'}],
  'title': 'Bitcoin Address Balance Distribution',
  'x_label': 'Date',
  'filename': 'Bitcoin_Address_Balance',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Network Activity',
  'description': 'The number of Bitcoin addresses holding at least a given balance, across thirteen '
                 'thresholds from a single satoshi to ten thousand coins.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Address Count', 'unit': 'count', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Hash Rate', 'data': 'hash_rate', 'axis': 'left'},
             {'name': 'Hash Rate 30 Day MA', 'data': '30_day_ma_hash_rate', 'axis': 'left'},
             {'name': 'Hash Rate 365 Day MA', 'data': '365_day_ma_hash_rate', 'axis': 'left'}],
  'title': 'Bitcoin Price & Hashrate',
  'x_label': 'Date',
  'filename': 'Bitcoin_Hashrate_Price',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': "Bitcoin's price against the total hashrate securing the network, with 30-day and "
                 '365-day averages of the computing power committed to mining.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'hash_rate', 'unit': 'hashrate', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Hash Rate 30-Day MA', 'data': '30_day_ma_hash_rate', 'axis': 'left'},
             {'name': 'Hash Rate 60-Day MA', 'data': '60_day_ma_hash_rate', 'axis': 'left'}],
  'title': 'Bitcoin Hash Ribbons',
  'x_label': 'Date',
  'filename': 'Bitcoin_Hash_Ribbons',
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': "Hash ribbons compare Bitcoin's 30-day and 60-day hashrate averages; their crossover "
                 'marks miner capitulation and the recovery that follows.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hash Rate (H/s)', 'unit': 'hashrate', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Difficulty', 'data': 'difficulty', 'axis': 'left'}],
  'title': 'Bitcoin Network Difficulty',
  'x_label': 'Date',
  'filename': 'Bitcoin_Difficulty',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': 'Mining difficulty is the target the network adjusts roughly every two weeks to hold '
                 'block times near ten minutes as hashrate changes.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Difficulty', 'unit': 'count', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Hash Price ($/TH/s)', 'data': 'hash_price_ths', 'axis': 'left'}],
  'title': 'Bitcoin Hash Price',
  'x_label': 'Date',
  'filename': 'Bitcoin_Hash_Price',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': 'Hash price is miner revenue per terahash per second per day, the dollar income a unit '
                 'of mining hardware earns and the core measure of mining economics.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hash Price ($/TH/s/day)', 'unit': 'USD/TH/s/day', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Miner Revenue', 'data': 'coinbase_sum_24h_usd', 'axis': 'left'},
             {'name': 'Miner Revenue 30 Day MA',
              'data': '30_day_ma_coinbase_sum_24h_usd',
              'axis': 'left'},
             {'name': 'Miner Revenue 365 Day MA',
              'data': '365_day_ma_coinbase_sum_24h_usd',
              'axis': 'left'}],
  'title': 'Bitcoin Miner Revenue',
  'x_label': 'Date',
  'filename': 'Bitcoin_Miner_Revenue',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': 'Total daily miner revenue in US dollars, the block subsidy plus transaction fees, '
                 'smoothed over 30-day and 365-day windows.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Miner Revenue', 'unit': 'USD', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Puell Multiple', 'data': 'puell_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Puell Multiple',
  'x_label': 'Date',
  'filename': 'Bitcoin_Puell_Multiple',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Mining and Security',
  'description': 'The Puell Multiple divides the daily dollar value of newly issued coins by its own '
                 '365-day average, measuring miner revenue against its norm.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Puell Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Thermocap Price', 'data': 'thermocap_price', 'axis': 'right'},
             {'name': '4x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_4',
              'axis': 'right'},
             {'name': '8x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_8',
              'axis': 'right'},
             {'name': '16x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_16',
              'axis': 'right'},
             {'name': '32x Thermocap Price Multiple',
              'data': 'thermocap_price_multiple_32',
              'axis': 'right'}],
  'title': 'Bitcoin Thermocap Multiple',
  'x_label': 'Date',
  'filename': 'Bitcoin_Thermocap_Multiples',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'On-chain Valuation',
  'description': 'Thermocap is the cumulative value paid to miners since genesis; thermocap price '
                 'divides it by supply to give a security-spend valuation floor.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Realized Price', 'data': 'realized_price', 'axis': 'right'},
             {'name': 'STH Realized Price', 'data': 'sth_realized_price', 'axis': 'right'},
             {'name': 'LTH Realized Price', 'data': 'lth_realized_price', 'axis': 'right'},
             {'name': '2x Realized Price', 'data': 'realizedcap_multiple_2', 'axis': 'right'},
             {'name': '3x Realized Price', 'data': 'realizedcap_multiple_3', 'axis': 'right'},
             {'name': '5x Realized Price', 'data': 'realizedcap_multiple_5', 'axis': 'right'},
             {'name': 'Realized Price Multiple ', 'data': 'CapMVRVCur', 'axis': 'left'}],
  'title': 'Bitcoin Realized Price',
  'x_label': 'Date',
  'filename': 'Bitcoin_Realized_Price',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2011-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'On-chain Valuation',
  'description': 'Realized price is the average on-chain acquisition cost of all circulating coins, '
                 "valuing each at the price it last moved rather than today's.",
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'MVRV Ratio', 'unit': 'ratio', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y2_type': 'log',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Realized Price', 'data': 'realized_price', 'axis': 'right'},
             {'name': 'Average Cap Price', 'data': 'average_cap_price', 'axis': 'right'},
             {'name': 'Delta Cap Price', 'data': 'delta_cap_price', 'axis': 'right'}],
  'title': 'Bitcoin Delta Cap',
  'x_label': 'Date',
  'filename': 'Bitcoin_Delta_Cap',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'On-chain Valuation',
  'description': 'Delta cap is realized cap minus average cap, a long-term valuation floor derived from '
                 'the difference between on-chain and lifetime average pricing.',
  'featured': False,
  'axes': {'right': {'label': 'Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'NVT Price 30 Day MA', 'data': '30_day_ma_nvt_price', 'axis': 'right'},
             {'name': 'NVT Price 365 Day MA', 'data': '365_day_ma_nvt_price', 'axis': 'right'}],
  'title': 'Bitcoin NVT Price',
  'x_label': 'Date',
  'filename': 'Bitcoin_NVT_Price',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'On-chain Valuation',
  'description': 'NVT price values Bitcoin from the value settled on-chain, applying the '
                 'network-value-to-transactions ratio in reverse to imply a fair price.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Net Unrealized Profit Loss', 'data': 'nupl', 'axis': 'left'}],
  'title': 'Bitcoin NUPL (Net Unrealized Profit/Loss)',
  'x_label': 'Date',
  'filename': 'Bitcoin_NUPL',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'On-chain Valuation',
  'description': 'Net Unrealized Profit/Loss is the total paper gain or loss held across all '
                 'circulating supply, expressed as a share of market capitalization.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'NUPL Ratio', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Adjusted BDD', 'data': 'adjusted_bdd', 'axis': 'left'},
             {'name': 'Adjusted BDD Mean', 'data': 'adjusted_bdd_mean', 'axis': 'left'}],
  'title': 'Bitcoin Days Destroyed, Supply-Adjusted',
  'x_label': 'Date',
  'filename': 'Bitcoin_Adjusted_BDD',
  'data_source': 'Data Source: BRK (Calculated)',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Behavior',
  'description': 'Bitcoin Days Destroyed weights each coin moved by how long it sat still; adjusting '
                 'for circulating supply makes the measure comparable across eras.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Adjusted BDD', 'unit': 'BTC-days', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'VOCD', 'data': 'vocd', 'axis': 'right'},
             {'name': 'MVOCD', 'data': 'mvocd', 'axis': 'right'},
             {'name': 'HODL Bank', 'data': 'hodl_bank_calc', 'axis': 'right'},
             {'name': 'Reserve Risk', 'data': 'reserve_risk_calc', 'axis': 'left'}],
  'title': 'Bitcoin HODL Bank & Reserve Risk',
  'x_label': 'Date',
  'filename': 'Bitcoin_HODL_Bank',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Behavior',
  'description': 'HODL Bank accumulates the opportunity cost borne by long-term holders; reserve risk '
                 'divides price by it to gauge conviction against price.',
  'featured': False,
  'axes': {'right': {'label': 'USD Value', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Reserve Risk', 'unit': 'ratio', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'SOPR', 'data': 'sopr_24h', 'axis': 'left'}],
  'title': 'Bitcoin SOPR (Spent Output Profit Ratio)',
  'x_label': 'Date',
  'filename': 'Bitcoin_SOPR',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2012-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Behavior',
  'description': 'Spent Output Profit Ratio compares the value of coins when spent to their value when '
                 'acquired, with 1.0 marking the aggregate break-even line.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'SOPR', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Supply in Profit %', 'data': 'supply_in_profit_pct', 'axis': 'left'},
             {'name': 'Supply in Loss %', 'data': 'supply_in_loss_pct', 'axis': 'left'}],
  'title': 'Bitcoin Supply in Profit vs Loss',
  'x_label': 'Date',
  'filename': 'Bitcoin_Supply_Profit_Loss',
  'data_source': 'Data Source: BRK',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Holder Behavior',
  'description': 'The share of circulating Bitcoin last moved below and above the current price, '
                 'splitting total supply into coins held in profit and in loss.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '% of Supply', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Power Expense ($0.05/kWh)', 'data': 'Electricity_Cost', 'axis': 'right'},
             {'name': 'Hayes Network Price Per BTC',
              'data': 'Hayes_Network_Price_Per_BTC',
              'axis': 'right'},
             {'name': 'Hayes Price Multiple', 'data': 'Hayes_Network_Price_Multiple', 'axis': 'left'}],
  'title': 'Bitcoin Production Price',
  'x_label': 'Date',
  'filename': 'Bitcoin_Production_Price',
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Bitcoin's cost of production, combining the power expense of mining a coin with the "
                 'Hayes cost-of-production network price.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Hayes Price Multiple', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Power Expense ($0.03/kWh)', 'data': 'Electricity_Cost_3c', 'axis': 'right'},
             {'name': 'Power Expense ($0.04/kWh)', 'data': 'Electricity_Cost_4c', 'axis': 'right'},
             {'name': 'Power Expense ($0.05/kWh)', 'data': 'Electricity_Cost_5c', 'axis': 'right'},
             {'name': 'Power Expense ($0.06/kWh)', 'data': 'Electricity_Cost_6c', 'axis': 'right'},
             {'name': 'Power Expense ($0.07/kWh)', 'data': 'Electricity_Cost_7c', 'axis': 'right'}],
  'title': 'Bitcoin Mining Electricity Cost',
  'x_label': 'Date',
  'filename': 'Bitcoin_Electricity_Cost',
  'filter_start_date': '2011-03-01',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "Bitcoin's electricity cost of production, the power expense of mining one coin, "
                 'modeled across tariffs from $0.03 to $0.07 per kWh.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price and Power Expense per BTC (USD)',
                     'unit': 'USD',
                     'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Power Law Price', 'data': 'power_law_price', 'axis': 'right'},
             {'name': 'BTC Price / Power Law Price',
              'data': 'power_law_price_multiple',
              'axis': 'left'}],
  'title': 'Bitcoin Power Law Model',
  'x_label': 'Date',
  'filename': 'Bitcoin_Power_Law_Model',
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': "The power law model fits Bitcoin's price to a straight line on a log-log scale "
                 'against time, treating growth as a function of network age.',
  'featured': True,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'BTC Price / Power Law Price', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Metcalfe Value (Any Balance)',
              'data': 'metcalfe_value_any_balance',
              'axis': 'right'},
             {'name': 'BTC Price / Metcalfe Value', 'data': 'metcalfe_price_multiple', 'axis': 'left'}],
  'title': 'Bitcoin Metcalfe Model',
  'x_label': 'Date',
  'filename': 'Bitcoin_Metcalfe_Model',
  'filter_start_date': '2010-07-01',
  'data_source': 'Data Source: Bitview',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Price Models',
  'description': 'Metcalfe values Bitcoin from the square of addresses holding any positive balance. '
                 'The price-to-model ratio uses that same Any Balance value.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'BTC Price / Metcalfe Value', 'unit': 'ratio', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Gold Marketcap', 'data': 'gold_marketcap_btc_price', 'axis': 'right'},
             {'name': 'Silver Marketcap', 'data': 'silver_marketcap_btc_price', 'axis': 'right'},
             {'name': 'Gold Jewellery', 'data': 'gold_jewellery_marketcap_btc_price', 'axis': 'right'},
             {'name': 'Gold Private Investment',
              'data': 'gold_private_investment_marketcap_btc_price',
              'axis': 'right'},
             {'name': 'Gold Country Holdings',
              'data': 'gold_official_country_holdings_marketcap_btc_price',
              'axis': 'right'},
             {'name': 'Gold Other / Industrial',
              'data': 'gold_other_marketcap_btc_price',
              'axis': 'right'}],
  'title': 'Bitcoin vs Gold Market Cap',
  'x_label': 'Date',
  'filename': 'Bitcoin_Gold',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Asset Comparisons',
  'description': "Bitcoin's market capitalization set against gold and silver, with gold broken into "
                 'jewelry, private investment, official holdings and industrial use.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Meta', 'data': 'META_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Amazon', 'data': 'AMZN_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Alphabet', 'data': 'GOOGL_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Microsoft', 'data': 'MSFT_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Apple', 'data': 'AAPL_mc_btc_price', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin Relative Valuation: Big Tech',
  'x_label': 'Date',
  'filename': 'Bitcoin_RV_stocks',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': "Bitcoin's price if its market capitalization matched a mega-cap technology company: "
                 'Meta, Amazon, Alphabet, Microsoft or Apple.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'NVIDIA', 'data': 'NVDA_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Broadcom', 'data': 'AVGO_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'TSMC', 'data': 'TSM_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Samsung Electronics',
              'data': '005930.KS_mc_btc_price',
              'optional': True,
              'axis': 'right'},
             {'name': 'Micron', 'data': 'MU_mc_btc_price', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin Relative Valuation: Semiconductors',
  'x_label': 'Date',
  'filename': 'Bitcoin_RV_Semiconductors',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2015-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': "Bitcoin's price if its market capitalization matched a leading semiconductor firm: "
                 'NVIDIA, Broadcom, TSMC, Samsung Electronics or Micron.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Berkshire Hathaway B',
              'data': 'BRK-B_mc_btc_price',
              'optional': True,
              'axis': 'right'},
             {'name': 'JPMorgan', 'data': 'JPM_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Goldman Sachs', 'data': 'GS_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Visa', 'data': 'V_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'PayPal', 'data': 'PYPL_mc_btc_price', 'optional': True, 'axis': 'right'},
             {'name': 'Block', 'data': 'XYZ_mc_btc_price', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin Relative Valuation: Financials',
  'x_label': 'Date',
  'filename': 'Bitcoin_RV_Financials',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2015-01-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Relative Valuation',
  'description': "Bitcoin's price if its market capitalization matched a major financial or payments "
                 'firm: Berkshire Hathaway, JPMorgan, Visa, PayPal or Block.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'United States', 'data': 'United_States_btc_price', 'axis': 'right'},
             {'name': 'China', 'data': 'China_btc_price', 'axis': 'right'},
             {'name': 'Eurozone', 'data': 'Eurozone_btc_price', 'axis': 'right'},
             {'name': 'Japan', 'data': 'Japan_btc_price', 'axis': 'right'},
             {'name': 'United Kingdom', 'data': 'United_Kingdom_btc_price', 'axis': 'right'},
             {'name': 'Switzerland', 'data': 'Switzerland_btc_price', 'axis': 'right'},
             {'name': 'India', 'data': 'India_btc_price', 'axis': 'right'},
             {'name': 'Australia', 'data': 'Australia_btc_price', 'axis': 'right'},
             {'name': 'Russia', 'data': 'Russia_btc_price', 'axis': 'right'}],
  'title': 'Bitcoin vs M0 Money Supply',
  'x_label': 'Date',
  'filename': 'Bitcoin_M0',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2010-07-01',
  'events': EVENTS,
  'family': 'timeseries',
  'category': 'Asset Comparisons',
  'description': "Bitcoin's market capitalization set against the M0 base money supply of nine major "
                 'economies, from the United States and China to Australia.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin YOY Return', 'data': 'price_close_YOY_change', 'axis': 'left'},
             {'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'}],
  'title': 'Bitcoin Year-Over-Year Return',
  'x_label': 'Date',
  'filter_start_date': '2015-01-01',
  'filename': 'Bitcoin_YOY_Return_Comparison',
  'data_source': 'Data Source: Bitview',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': "Bitcoin's year-over-year return, the percentage change in price against the same date "
                 'twelve months earlier, plotted against price itself.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price (USD)', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': 'Year Over Year Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin Price', 'data': 'price_close', 'axis': 'right'},
             {'name': 'Bitcoin 4 Year CAGR', 'data': 'price_close_4_Year_CAGR', 'axis': 'left'}],
  'title': 'Bitcoin 4-Year CAGR',
  'x_label': 'Date',
  'filter_start_date': '2015-01-01',
  'filename': 'Bitcoin_CAGR',
  'data_source': 'Data Source: Bitview',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': "Bitcoin's four-year compound annual growth rate, the annualized return an investor "
                 'would have earned over any rolling four-year holding period.',
  'featured': False,
  'axes': {'right': {'label': 'Bitcoin Price', 'unit': 'USD', 'mode': 'log'},
           'left': {'label': '4 Year CAGR (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin', 'data': 'price_close_4_Year_CAGR', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_4_Year_CAGR', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_4_Year_CAGR',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin 4-Year CAGR vs Other Assets',
  'x_label': 'Date',
  'filename': 'Bitcoin_CAGR_Comparison',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': '2015-05-01',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': 'Four-year compound annual growth rates for Bitcoin and eight benchmarks, covering '
                 'equities, technology, financials, gold, bonds, the dollar and miners.',
  'featured': False,
  'axes': {'right': {'label': '4 Year CAGR (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': '4Y'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin', 'data': 'price_close_MTD_change', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_MTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_MTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_MTD_change',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin MTD Return vs Other Assets',
  'x_label': 'Date',
  'filename': 'Bitcoin_MTD_Return_Comparison',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': 'report_month_start',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': 'Month-to-date returns for Bitcoin and eight benchmarks, covering equities, '
                 'technology, financials, gold, bonds, the dollar and Bitcoin miners.',
  'featured': False,
  'axes': {'right': {'label': 'Month To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'MTD'},
 {'x_data': 'time',
  'y_data': [{'name': 'Bitcoin', 'data': 'price_close_YTD_change', 'axis': 'right'},
             {'name': 'S&P 500 Index ETF',
              'data': 'SPY_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Nasdaq-100 ETF',
              'data': 'QQQ_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Technology Sector ETF',
              'data': 'XLK_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Financials Sector ETF',
              'data': 'XLF_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Gold ETF', 'data': 'GLD_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'Aggregate Bond ETF',
              'data': 'AGG_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'US Dollar Index',
              'data': 'DX-Y.NYB_close_YTD_change',
              'optional': True,
              'axis': 'right'},
             {'name': 'Bitcoin Miners ETF',
              'data': 'WGMI_close_YTD_change',
              'optional': True,
              'axis': 'right'}],
  'title': 'Bitcoin YTD Return vs Other Assets',
  'x_label': 'Date',
  'filename': 'Bitcoin_YTD_Return_Comparison',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': 'report_year_start',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': 'Year-to-date returns for Bitcoin and eight benchmarks, covering equities, technology, '
                 'financials, gold, bonds, the dollar and Bitcoin miners.',
  'featured': False,
  'axes': {'right': {'label': 'Year To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'YTD'},
 {'x_data': 'time',
  'y_data': [{'name': 'BTC', 'data': 'price_close_YTD_change', 'axis': 'right'},
             {'name': 'SPY', 'data': 'SPY_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'QQQ', 'data': 'QQQ_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'VTI', 'data': 'VTI_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'VXUS', 'data': 'VXUS_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLK', 'data': 'XLK_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLF', 'data': 'XLF_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLE', 'data': 'XLE_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'XLRE', 'data': 'XLRE_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'DXY', 'data': 'DX-Y.NYB_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'GLD', 'data': 'GLD_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'AGG', 'data': 'AGG_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'SPGSCI', 'data': '^SPGSCI_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'MSTR', 'data': 'MSTR_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'XYZ', 'data': 'XYZ_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'COIN', 'data': 'COIN_close_YTD_change', 'optional': True, 'axis': 'right'},
             {'name': 'WGMI', 'data': 'WGMI_close_YTD_change', 'optional': True, 'axis': 'right'}],
  'title': 'Bitcoin YTD Return vs 16 Benchmarks',
  'x_label': 'Date',
  'filename': 'Bitcoin_YTD_Return_Comparison_full',
  'data_source': 'Data Source: Bitview',
  'filter_start_date': 'report_year_start',
  'family': 'timeseries',
  'category': 'Returns and Performance',
  'description': 'Year-to-date returns for Bitcoin and sixteen benchmarks: US and international '
                 'equities, sector funds, commodities, bonds and Bitcoin-linked stocks.',
  'featured': False,
  'axes': {'right': {'label': 'Year To Date Return (Percentage)', 'unit': 'percent', 'mode': 'linear'}},
  'default_range': 'YTD'}]
